services:
    app:
      image: seu-website:1.0
      build:
        context: ./
        dockerfile: Dockerfile
      ports:
        - '3006:3000'
      restart: unless-stopped
      command: ["npm", "run", "start"]