import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class"],
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        main: {
          primary: "var(--main-colors-primary)",
          secondary: "var(--main-colors-secondary)",
          black: "var(--main-colors-black)",
          white: "var(--main-colors-white)",
          text: "var(--main-colors-text)",
        },
        "p-tints": {
          "tint-2": "var(--p-tints-tint-2)",
          "tint-3": "var(--p-tints-tint-3)",
          "tint-5": "var(--p-tints-tint-5)",
          "tint-10": "var(--p-tints-tint-10)",
          "tint-15": "var(--p-tints-tint-15)",
          "tint-20": "var(--p-tints-tint-20)",
          "tint-30": "var(--p-tints-tint-30)",
          "tint-40": "var(--p-tints-tint-40)",
          "tint-50": "var(--p-tints-tint-50)",
          "tint-60": "var(--p-tints-tint-60)",
          "tint-70": "var(--p-tints-tint-70)",
          "tint-80": "var(--p-tints-tint-80)",
          "tint-90": "var(--p-tints-tint-90)",
        },
        "p2-tints": {
          "tint-2": "var(--p2-tints-tint-2)",
          "tint-3": "var(--p2-tints-tint-3)",
          "tint-5": "var(--p2-tints-tint-5)",
          "tint-10": "var(--p2-tints-tint-10)",
          "tint-15": "var(--p2-tints-tint-15)",
          "tint-20": "var(--p2-tints-tint-20)",
          "tint-30": "var(--p2-tints-tint-30)",
          "tint-40": "var(--p2-tints-tint-40)",
          "tint-50": "var(--p2-tints-tint-50)",
          "tint-60": "var(--p2-tints-tint-60)",
          "tint-70": "var(--p2-tints-tint-70)",
          "tint-80": "var(--p2-tints-tint-80)",
          "tint-90": "var(--p2-tints-tint-90)",
        },
        "p-shades": {
          "shade-30": "var(--p-shades-shade-30)",
          "shade-50": "var(--p-shades-shade-50)",
          "shade-60": "var(--p-shades-shade-60)",
          "shade-70": "var(--p-shades-shade-70)",
          "shade-80": "var(--p-shades-shade-80)",
          "shade-90": "var(--p-shades-shade-90)",
        },
        "s-tints": {
          "tint-50": "var(--s-tints-tint-50)",
          "tint-60": "var(--s-tints-tint-60)",
          "tint-80": "var(--s-tints-tint-80)",
          "tint-90": "var(--s-tints-tint-90)",
        },
        black: {
          "tint-2": "var(--black-tint-2)",
          "tint-3": "var(--black-tint-3)",
          "tint-5": "var(--black-tint-5)",
          "tint-8": "var(--black-tint-8)",
          "tint-10": "var(--black-tint-10)",
          "tint-15": "var(--black-tint-15)",
          "tint-20": "var(--black-tint-20)",
          "tint-30": "var(--black-tint-30)",
          "tint-40": "var(--black-tint-40)",
          "tint-50": "var(--black-tint-50)",
          "tint-60": "var(--black-tint-60)",
          "tint-70": "var(--black-tint-70)",
          "tint-80": "var(--black-tint-80)",
          "tint-90": "var(--black-tint-90)",
        },
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        chart: {
          "1": "hsl(var(--chart-1))",
          "2": "hsl(var(--chart-2))",
          "3": "hsl(var(--chart-3))",
          "4": "hsl(var(--chart-4))",
          "5": "hsl(var(--chart-5))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
export default config;
